# Generated by Django 4.2.7 on 2023-11-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('users_id', models.BigIntegerField()),
                ('users_email', models.CharField(max_length=211)),
                ('users_name', models.CharField(blank=True, max_length=100)),
                ('users_key', models.CharField(max_length=20)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
