# Generated by Django 4.2.7 on 2023-11-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer_group',
            fields=[
                ('streamer_group_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('streamer_group_id', models.BigIntegerField()),
                ('streamer_group_name', models.CharField(max_length=50)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='users_email',
            field=models.EmailField(max_length=211),
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('streamer_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('streamer_id', models.BigIntegerField()),
                ('streamer_api_key', models.CharField(max_length=20)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('streamer_group_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.streamer_group')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream_id', models.BigIntegerField()),
                ('stream_api_key', models.CharField(max_length=20)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('streamer_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.streamer')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('label_id', models.BigIntegerField()),
                ('label_name', models.CharField(blank=True, max_length=50)),
                ('is_share', models.BooleanField(default='false')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.users')),
                ('stream_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('favorite_id', models.BigIntegerField()),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('stream_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.stream')),
                ('streamer_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.streamer')),
                ('users_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.users')),
            ],
        ),
    ]
