# Generated by Django 4.2.7 on 2023-12-12 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_app', '0002_streamer_group_alter_users_users_email_streamer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_id',
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_id',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='stream_id',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='streamer_id',
        ),
        migrations.RemoveField(
            model_name='streamer_group',
            name='streamer_group_id',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='users_oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
