# Generated by Django 4.2.7 on 2023-12-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_remove_favorite_favorite_id_remove_label_label_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='streamer_group_oid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_app.streamer_group'),
        ),
    ]
