# Generated by Django 4.2.7 on 2023-12-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_alter_streamer_streamer_group_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='stream_oid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_app.stream'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='streamer_oid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_app.streamer'),
        ),
    ]
