# Generated by Django 4.2.7 on 2023-12-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_alter_favorite_stream_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
