# Generated by Django 4.2.7 on 2023-12-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_alter_label_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='streamer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
