# Generated by Django 4.2.7 on 2023-12-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_streamer_streamer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
